# Generated by Django 4.2.6 on 2023-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
