# Generated by Django 4.2.6 on 2023-10-21 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_database_api.game'),
        ),
    ]
