import os, django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'setup.settings')
django.setup()

from faker import Faker
from games_database_api.models import Genre,Developer,Franchise,Game,GameGenre,Publisher

fake = Faker('pt_BR')

def create_genres():
    genre = Genre(name="survival horror")
    genre.save()    
    genre = Genre(name="action")
    genre.save()
    genre = Genre(name="action/adventure")
    genre.save()
    genre = Genre(name="fps")
    genre.save()
    genre = Genre(name="hack and slash")
    genre.save()
    genre = Genre(name="metroidvania")
    genre.save()
    genre = Genre(name="souls like")
    genre.save()
    genre = Genre(name="jrpg")
    genre.save()
    genre = Genre(name="rpg")
    genre.save()
    genre = Genre(name="point and click")
    genre.save()
    genre = Genre(name="fighting")
    genre.save()

def create_developers():
    developer = Developer(name="from software")
    developer.save()    
    developer = Developer(name="capcom")
    developer.save()
    developer = Developer(name="konami")
    developer.save()
    developer = Developer(name="square enix")
    developer.save()
    developer = Developer(name="eidos")
    developer.save()
    developer = Developer(name="io interactive")
    developer.save()
    developer = Developer(name="rockstar")
    developer.save()
    developer = Developer(name="koei tecmo")
    developer.save()
    developer = Developer(name="netherealm")
    developer.save()
    developer = Developer(name="devolver digital")
    developer.save()
    developer = Developer(name="infinity ward")
    developer.save()

def create_publishers():
    publisher = Publisher(name="bandai namco")
    publisher.save()    
    publisher = Publisher(name="activision")
    publisher.save()
    publisher = Publisher(name="e&a")
    publisher.save()
    publisher = Publisher(name="capcom")
    publisher.save()
    publisher = Publisher(name="konami")
    publisher.save()
    publisher = Publisher(name="taketwo")
    publisher.save()
    publisher = Publisher(name="warner bros")
    publisher.save()
    publisher = Publisher(name="koei tecmo")
    publisher.save()
    publisher = Publisher(name="square enix")
    publisher.save()
    publisher = Publisher(name="devolver digital")
    publisher.save()

def create_franchises():
    franchises = Franchise(name="resident evil")
    franchises.save()    
    franchises = Franchise(name="silent hill")
    franchises.save()
    franchises = Franchise(name="call of duty")
    franchises.save()
    franchises = Franchise(name="battlefield")
    franchises.save()
    franchises = Franchise(name="dark souls")
    franchises.save()
    franchises = Franchise(name="the witcher")
    franchises.save()
    franchises = Franchise(name="final fantasy")
    franchises.save()
    franchises = Franchise(name="persona")
    franchises.save()
    franchises = Franchise(name="mortal kombat")
    franchises.save()
    franchises = Franchise(name="tomb raider")
    franchises.save()

def create_games():
    game = Game(name="resident evil 4", franchise= Franchise.objects.get(name="resident evil"), developer= Developer.objects.get(name="capcom"), publisher = Publisher.objects.get(name="capcom"), release_date = '2005-01-11' )
    game.save()    
    game = Game(name="resident evil 4 remake", franchise= Franchise.objects.get(name="resident evil"), developer= Developer.objects.get(name="capcom"), publisher = Publisher.objects.get(name="capcom"), release_date = '2023-03-24' )
    game.save()
    game = Game(name="call of duty modern warfare 3 (2023)", franchise= Franchise.objects.get(name="call of duty"), developer= Developer.objects.get(name="infinity ward"), publisher = Publisher.objects.get(name="activision"), release_date = '2023-11-10' )
    game.save()
    game = Game(name="mortal kombat 1 (2023)", franchise= Franchise.objects.get(name="mortal kombat"), developer= Developer.objects.get(name="netherealm"), publisher = Publisher.objects.get(name="warner bros"), release_date = '2023-09-14' )
    game.save()

def create_gamegenre():
     gamegenre = GameGenre(game=Game.objects.get(name="resident evil 4"),genre=Genre.objects.get(name='survival horror'))
     gamegenre.save()    
     gamegenre = GameGenre(game=Game.objects.get(name="resident evil 4"),genre=Genre.objects.get(name='action/adventure'))
     gamegenre.save() 
     gamegenre = GameGenre(game=Game.objects.get(name="resident evil 4 remake"),genre=Genre.objects.get(name='survival horror'))
     gamegenre.save()    
     gamegenre = GameGenre(game=Game.objects.get(name="resident evil 4 remake"),genre=Genre.objects.get(name='action/adventure'))
     gamegenre.save() 
     gamegenre = GameGenre(game=Game.objects.get(name="call of duty modern warfare 3 (2023)"),genre=Genre.objects.get(name='fps'))
     gamegenre.save()      
     gamegenre = GameGenre(game=Game.objects.get(name="mortal kombat 1 (2023)"),genre=Genre.objects.get(name='fighting'))
     gamegenre.save()       

create_developers()
create_franchises()
create_genres()
create_publishers()
create_games()
create_gamegenre()